### ISSUE TITLE
Referencing with curly braces

### ISSUE THREAD

**Issue by mbojan** [tomduck/pandoc-fignos#6] opened 2015-12-10 16:43 UTC
... does not work for me:

Markdown input:

```
Some text here

![Caption here](legenda.png) {#fig:legend}

Referencing figure 1a:

1. No braces @fig:legend a
2. with braces {@fig:legend}a.
```

Processed with

```
/usr/bin/pandoc +RTS -K512m -RTS test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --smart --email-obfuscation none --filter pandoc-fignos --standalone --section-divs --table-of-contents --toc-depth 3 --template /home/mbojan/R/library/3.2/rmarkdown/rmd/h/default.html --number-sections --variable 'theme:bootstrap' --include-in-header /tmp/RtmpkT19BC/rmarkdown-str496b1622d1ac.html --no-highlight --variable highlightjs=test_files/highlight 
```

creates HTML output (only relevant part):

```
<p>Some text here</p>
<a name="fig:legend"></a>
<div class="figure">
<img src="legenda.png" alt="Figure 1. Caption here" />
<p class="caption">Figure 1. Caption here</p>
</div>
<p>Referencing figure 1a:</p>
<ol style="list-style-type: decimal">
<li>No braces <a href="#fig:legend">1</a> a</li>
<li>with braces <a href="mailto:{@fig">{@fig</a>:legend}a.</li>
</ol>
```

As you can see the reference in item 2 is interpreted as an email address. If I switch off the `autolink_bare_uris` extension (not shown) the link is correctly produced, but the curly braces are not removed (as advertised in your README).

My goal is to have references to, say, "1a" where only "1" is a link and "a" is added as a plain text. Any suggestions? Is it possible to achieve this with simple `@fig:legend` reference to get "1a" without the space between `1` and `a`?

**Comment by mbojan** [comment] 2015-12-11 12:31
~~I now see that there must be some conflict with one of the other options of `pandoc`, because running "vanilla" with no additional options apart from `--filter pandoc-fignos` produces correct results.~~

~~I'm trying to figure-out which option causes the trouble. Any ideas?~~

Above is not correct, actually it is not working. Curly braces still in the output.

**Comment by mbojan** [comment] 2015-12-11 12:57
OK, I think I am nailing the problem. Looks like removing braces does not work in lists? Try the following input file:

```
Some text here

![Caption here](legenda.png) {#fig:legend}

Referencing figure 1a:

1. No braces @fig:legend a
2. with braces {@fig:legend}

And here outside of a list {@fig:legend} seem to work
```

I think this problem also happens in your other scripts `pandoc-eqnos`, see e.g. this https://github.com/tomduck/pandoc-eqnos/issues/5

**Comment by tomduck** [comment] 2015-12-27 13:34
Sorry for the delay.  I'm on it, and should have a fix within a day or two.

**Comment by tomduck** [comment] 2015-12-30 20:11
I have reproduced the problem and am working on a fix.

**Comment by tomduck** [comment] 2015-12-30 20:34
I have pushed a new version to github.  Would you mind installing from source and confirming that it works for you?  If everything is OK, then I will post a new version to pypi.

Given that you tracked down the source of the error, the fix was straight-forward.  Thanks for your help!

**Comment by tomduck** [comment] 2015-12-31 16:57
I just posted pandoc-fignos 0.5 to pypi.  Please let me know if it works for you.  Cheers. :o)

**Comment by mbojan** [comment] 2016-01-07 08:56
Hi. Sorry for late reply. I was on holiday in wilderness without internet.

I installed the update, and everything seems to work correctly provided that I **do not use** `autolink_bare_uris` extension. 

Thanks for the fix. This solves the problem for me.

**Comment by tomduck** [comment] 2016-01-07 16:06
Thanks, @mbojan.  I have reproduced the `autolink_bare_uris` problem using the markdown you provided.  For reference, my build command is

```
pandoc test.md --from markdown+autolink_bare_uris  --output test.html --filter pandoc-fignos --standalone
```

I'm re-opening this issue so that it gets looked after.

**Comment by tomduck** [comment] 2016-01-08 00:00
I see what the problem is.  With `autolink_bare_uris` enabled, pandoc treats text like

```
{@fig:legend}
```

as if `{@fig` is an email address.  Eek!

**Comment by tomduck** [comment] 2016-01-08 05:39
I think that I have the `autolink_bare_uris` problem solved.  Could you please install from source to see if it works for you?  Thanks for your help!

**Comment by mbojan** [comment] 2016-01-08 12:11
OK, I'll test. I don't know Python at all. How do I install from source?

**Comment by tomduck** [comment] 2016-01-09 22:36
To make this simpler, I decided to post a new release (0.7.2) to pipy.  Could you please test it as normal?  Thanks in advance.

**Comment by tomduck** [comment] 2016-01-23 18:02
I'm closing this Issue because I am confident everything is working.  Please re-open it if you are still having problems.  Thanks!

**Closed as completed by tomduck** 2016-01-23 18:02 UTC
Labels: bug
