### ISSUE TITLE
Error when processing TeX document

### ISSUE THREAD

**Issue by vikasrawal** [tomduck/pandoc-fignos#31] opened 2016-11-15 03:02 UTC
I get a similar error while using pandoc-tablenos. Pandoc was installed using homebrew, and pandoc-tablenos and pandoc-fignos using pip3. Is that a problem?

Traceback (most recent call last):
  File "/usr/local/bin/pandoc-fignos", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pandoc_fignos.py", line 377, in main
    altered)
  File "/usr/local/lib/python3.5/site-packages/pandoc_fignos.py", line 375, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/usr/local/lib/python3.5/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/usr/local/lib/python3.5/site-packages/pandocxnos/core.py", line 615, in process_refs
    _process_refs(value, labels)
  File "/usr/local/lib/python3.5/site-packages/pandocxnos/core.py", line 119, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pandocxnos/core.py", line 570, in _process_refs
    _get_label(v['t'], v['c']) in labels:
TypeError: unhashable type: 'list'
pandoc: Error running filter pandoc-fignos
Filter returned error status

**Comment by tomduck** [comment] 2016-11-16 18:30
Note: This report follows a [similar one](https://github.com/tomduck/pandoc-tablenos/issues/4) on pandoc-tablenos.

**Comment by tomduck** [comment] 2016-11-17 16:22
I revised the documentation to make clear that pandoc-fignos is for processing markdown documents only.  Given that this is a duplicate of [Issue #4](https://github.com/tomduck/pandoc-tablenos/issues/4) with pandoc-tablenos (where it was first submitted), I am closing this one.

**Closed as completed by tomduck** 2016-11-17 16:22 UTC
Labels: duplicate
